import GameUIManager from '../../../Backend/GameLogic/GameUIManager';
import AsteroidRenderer from './Entities/AsteroidRenderer';
import BackgroundRenderer from './Entities/BackgroundRenderer';
import BeltRenderer from './Entities/BeltRenderer';
import BlackDomainRenderer from './Entities/BlackDomainRenderer';
import CircleRenderer from './Entities/CircleRenderer';
import LineRenderer from './Entities/LineRenderer';
import { MineRenderer } from './Entities/MineRenderer';
import PlanetRenderer from './Entities/PlanetRenderer';
import PlanetRenderManager from './Entities/PlanetRenderManager';
import { QuasarRenderer } from './Entities/QuasarRenderer';
import RectRenderer from './Entities/RectRenderer';
import RingRenderer from './Entities/RingRenderer';
import { RuinsRenderer } from './Entities/RuinsRenderer';
import { SpacetimeRipRenderer } from './Entities/SpacetimeRipRenderer';
import { SpriteRenderer } from './Entities/SpriteRenderer';
import TextRenderer from './Entities/TextRenderer';
import VoyageRenderer from './Entities/VoyageRenderer';
import { WormholeRenderer } from './Entities/WormholeRenderer';
import Overlay2DRenderer from './Overlay2DRenderer';
import { UIRenderer } from './UIRenderer';
import { GameGLManager } from './WebGL/GameGLManager';
declare class Renderer {
    static instance: Renderer | null;
    canvas: HTMLCanvasElement;
    glCanvas: HTMLCanvasElement;
    bufferCanvas: HTMLCanvasElement;
    frameRequestId: number;
    gameUIManager: GameUIManager;
    frameCount: number;
    now: number;
    glManager: GameGLManager;
    overlay2dRenderer: Overlay2DRenderer;
    lineRenderer: LineRenderer;
    circleRenderer: CircleRenderer;
    textRenderer: TextRenderer;
    rectRenderer: RectRenderer;
    bgRenderer: BackgroundRenderer;
    planetRenderer: PlanetRenderer;
    asteroidRenderer: AsteroidRenderer;
    beltRenderer: BeltRenderer;
    mineRenderer: MineRenderer;
    spriteRenderer: SpriteRenderer;
    quasarRenderer: QuasarRenderer;
    spacetimeRipRenderer: SpacetimeRipRenderer;
    ruinsRenderer: RuinsRenderer;
    ringRenderer: RingRenderer;
    blackDomainRenderer: BlackDomainRenderer;
    uiRenderManager: UIRenderer;
    planetRenderManager: PlanetRenderManager;
    voyageRenderManager: VoyageRenderer;
    wormholeRenderManager: WormholeRenderer;
    private previousRenderTimestamp;
    private constructor();
    private setup;
    static destroy(): void;
    static initialize(canvas: HTMLCanvasElement, glCanvas: HTMLCanvasElement, bufferCanvas: HTMLCanvasElement, gameUIManager: GameUIManager): Renderer;
    private recordRender;
    private loop;
    private draw;
}
export default Renderer;
