/// <reference types="react" />
import { TooltipName } from '@darkforest_eth/types';
export declare function NetworkHealthPane(): JSX.Element;
export declare function WithdrawSilverButton(): JSX.Element;
export declare function DefenseMultiplierPane(): JSX.Element;
export declare function EnergyCapMultiplierPane(): JSX.Element;
export declare function EnergyGrowthMultiplierPane(): JSX.Element;
export declare function RangeMultiplierPane(): JSX.Element;
export declare function SpeedMultiplierPane(): JSX.Element;
export declare function DepositArtifactPane(): JSX.Element;
export declare function DeactivateArtifactPane(): JSX.Element;
export declare function WithdrawArtifactPane(): JSX.Element;
export declare function ActivateArtifactPane(): JSX.Element;
export declare function TimeUntilActivationPossiblePane(): JSX.Element;
export declare function TwitterHandleTooltipPane(): JSX.Element;
export declare function RankTooltipPane(): JSX.Element;
export declare function ScoreTooltipPane(): JSX.Element;
export declare function MiningPauseTooltipPane(): JSX.Element;
export declare function MiningTargetTooltipPane(): JSX.Element;
export declare function CurrentMiningTooltipPane(): JSX.Element;
export declare function BonusTooltipPane(): JSX.Element;
export declare function SilverTooltipPane(): JSX.Element;
export declare function EnergyTooltipPane(): JSX.Element;
export declare function PlanetRankTooltipPane(): JSX.Element;
export declare function MaxLevelTooltipPane(): JSX.Element;
export declare function SilverProdTooltipPane(): JSX.Element;
export declare function SelectedSilverTooltipPane(): JSX.Element;
export declare function RangeTooltipPane(): JSX.Element;
export declare function MinEnergyTooltipPane(): JSX.Element;
export declare function Time50TooltipPane(): JSX.Element;
export declare function Time90TooltipPane(): JSX.Element;
export declare function EnergyGrowthTooltipPane(): JSX.Element;
export declare function SilverGrowthTooltipPane(): JSX.Element;
export declare function SilverCapTooltipPane(): JSX.Element;
export declare function PiratesTooltipPane(): JSX.Element;
export declare function UpgradesTooltipPane(): JSX.Element;
export declare function ModalHelpTooltipPane(): JSX.Element;
export declare function ModalPlanetDetailsTooltipPane(): JSX.Element;
export declare function ModalLeaderboardTooltipPane(): JSX.Element;
export declare function ModalPlanetDexTooltipPane(): JSX.Element;
export declare function ModalUpgradeDetailsTooltipPane(): JSX.Element;
export declare function ModalTwitterVerificationTooltipPane(): JSX.Element;
export declare function ModalBroadcastTooltipPane(): JSX.Element;
export declare function BonusEnergyCapTooltipPane(): JSX.Element;
export declare function BonusEnergyGroTooltipPane(): JSX.Element;
export declare function BonusRangeTooltipPane(): JSX.Element;
export declare function BonusSpeedTooltipPane(): JSX.Element;
export declare function BonusDefenseTooltipPane(): JSX.Element;
export declare function BonusSpaceJunkTooltipPane(): JSX.Element;
export declare function ClowntownTooltipPane(): JSX.Element;
export declare function TooltipContent({ name }: {
    name: TooltipName | undefined;
}): JSX.Element;
