export declare const planetNameWords: string[];
export declare const planetTagAdj: string[];
export declare const planetTagNoun: string[];
export declare const blurbGrammar: {
    geography: any[];
    populates: string[];
    landscape: string[];
    stretch: string[];
    noun: string[];
    verb: string[];
    adj: string[];
    eyecansee: any[];
    air: string[];
    fruit: string[];
    colors: string[];
    habitat: string[];
    populate: string[];
    species: string[];
    many: string[];
    bloom: string[];
    flora: string[];
    descair: any[];
    gravity: string[];
    funfact: string[];
};
export declare const blurb2grammar: {
    learned: string[];
    live: string[];
    sun: string[];
    flock: string[];
    bads: string[];
    sends: string[];
    sometimes: string[];
    years: string[];
    removed: string[];
    throwing: string[];
    warbears: string[];
    lesson: string[];
    friends: string[];
    alongtheway: string[];
    treasure: string[];
    friend: string[];
    made: string[];
    chocolates: string[];
    life: string[];
    box: string[];
    chocolate: string[];
    know: string[];
    get: string[];
    willway: string[];
    when: string[];
    theres: string[];
    will: string[];
    way: string[];
};
