import { EthAddress, Planet, Upgrade, UpgradeBranchName } from '@darkforest_eth/types';
import { BigInteger } from 'big-integer';
import { StatIdx } from '../../_types/global/GlobalTypes';
export declare const ONE_DAY: number;
declare type NestedBigIntArray = (BigInteger | string | NestedBigIntArray)[];
declare type NestedStringArray = (string | NestedStringArray)[];
export declare const hexifyBigIntNestedArray: (arr: NestedBigIntArray) => NestedStringArray;
export declare const getUpgradeStat: (upgrade: Upgrade, stat: StatIdx) => number;
export declare const hslStr: (h: number, s: number, l: number) => string;
export declare const getPlayerColor: (player: EthAddress) => string;
export declare const getOwnerColor: (planet: Planet) => string;
export declare const getRandomActionId: () => string;
export declare const getFormatProp: (planet: Planet | undefined, prop: string) => string;
export declare const getPlanetRank: (planet: Planet | undefined) => number;
export declare const getPlanetShortHash: (planet: Planet | undefined) => string;
export declare const getPlayerShortHash: (address: EthAddress) => string;
export declare const isFullRank: (planet: Planet | undefined) => boolean;
export declare const upgradeName: (branchName: UpgradeBranchName) => string;
export declare const getPlanetMaxRank: (planet: Planet | undefined) => number;
export declare const titleCase: (title: string) => string;
export {};
